# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: name: 24f2000717@ds.study.iitm.ac.in
        run: echo Hello, world!

      - name: prime-cache-08f4942
        id: cache-step
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            node_modules
          key: cache-08f4942

      - name: Report cache status
        run: |
          echo "Cache hit status: ${{ steps.cache-step.outputs.cache-hit }}"

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
