name: Daily Commit Workflow

on:
  schedule:
    - cron: '19 5 * * *'  # 05:19 UTC daily
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Commit daily file
        run: |
          # Overwrite the file every run to ensure a change
          echo "24f2000717@ds.study.iitm.ac.in $(date +'%Y-%m-%d %H:%M:%S')" > daily_commit.txt
          
          git config user.name "24f2000717@ds.study.iitm.ac.in"
          git config user.email "24f2000717@ds.study.iitm.ac.in"
          
          git add daily_commit.txt
          # Force commit even if content is the same
          git commit --allow-empty -m "Daily commit from workflow $(date +'%Y-%m-%d %H:%M:%S')"
          
          # Push using GitHub-provided token
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/hrithivkgolu/IITM.git
